const mongoose = require('mongoose');
// This schema defines the structure for storing class information, including the class name, associated school, teacher, and subjects.
//this should be generated by the school manager before entering the students

const classSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    schoolId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'School',
        required: true
    },
    teacherId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Teacher',
        required: true
    },
    subjects: [{
        name: { type: String, required: true },
        teacherId: { type: mongoose.Schema.Types.ObjectId, ref: 'Teacher' }
    }]
});

module.exports = mongoose.model('Class', classSchema);
