const mongoose = require('mongoose');

// This schema defines the structure for storing student information, including their admission details, class, attendance, and marks.
const studentSchema = new mongoose.Schema({
    admissionNumber:{type:String,
        required:true
    },
    userId:{ // automatically generated by the server
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required: true
    },
    classId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Class',
        required:true
    },
    attendancePercentage: {
        type: Number,
        default: 0
      },
    parentPhoneNumber:{
        type:String,
        required:true
    },
    Marks:[{
        subjectName:{type:String},
        marksObtained:{type:Number,default:null}
    }],
})

module.exports = mongoose.model("Student",studentSchema);